[theme]
base="dark"
primaryColor="#06b6d4"
backgroundColor="#050505"
secondaryBackgroundColor="#111827"
textColor="#e5e7eb"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
